def get_majors():
    return [
        ("Applied Physics", 0),
        ("Astronomy", 0),
        ("Biochemistry", 1),
        ("Biochemistry", 2),
        ("Bioinformatics: Computer Science Emphasis", 0),
        ("Bioinformatics: Ecology and Evolutionary Biology Emphasis", 0),
        ("Bioinformatics: Molecular and Cellular Biology Emphasis", 0),
        ("Bioinformatics: Systems Biology Emphasis", 0),
        ("Biology: Biomedical Sciences Emphasis", 0),
        ("Biology: Organismal Biology Emphasis", 0),
        ("Chemistry", 1),
        ("Chemistry", 2),
        ("Computer Science", 1),
        ("Computer Science", 2),
        ("Ecology and Evolutionary Biology", 1),
        ("Ecology and Evolutionary Biology", 2),
        ("Geosciences: Earth, Ocean, and Climate Emphasis", 0),
        ("Geosciences: Geology Emphasis", 0),
        ("Geosciences: Geophysics Emphasis", 0),
        ("Hydrology and Atmospheric Sciences: Atmospheric Sciences Emphasis", 0),
        (
            "Hydrology and Atmospheric Sciences: Environmental Hydrology and Water Resources Emphasis",
            0,
        ),
        ("Mathematics: Applied Emphasis", 1),
        ("Mathematics: Applied Emphasis", 2),
        ("Mathematics: Comprehensive Emphasis", 1),
        ("Mathematics: Comprehensive Emphasis", 2),
        ("Mathematics: Computer Science Emphasis", 1),
        ("Mathematics: Computer Science Emphasis", 2),
        ("Mathematics: Economics and Business Emphasis", 1),
        ("Mathematics: Economics and Business Emphasis", 2),
        ("Mathematics: Education Emphasis", 1),
        ("Mathematics: Education Emphasis", 2),
        ("Mathematics: Life Sciences Emphasis", 1),
        ("Mathematics: Life Sciences Emphasis", 2),
        ("Mathematics: Probability and Statistics Emphasis", 1),
        ("Mathematics: Probability and Statistics Emphasis", 2),
        ("Molecular and Cellular Biology", 0),
        ("Molecular and Cellular Biology: Education and Communication Emphasis", 0),
        ("Molecular and Cellular Biology: Genetics and Human Health Emphasis", 0),
        ("Molecular and Cellular Biology: Systems and Big Data Biology Emphasis", 0),
        ("Neuroscience and Cognitive Science", 0),
        ("Neuroscience and Cognitive Science: Cognition Emphasis", 0),
        ("Neuroscience and Cognitive Science: Computation Emphasis", 0),
        ("Neuroscience and Cognitive Science: Development and Aging Emphasis", 0),
        (
            "Neuroscience and Cognitive Science: Language and Communication Science Emphasis",
            0,
        ),
        ("Neuroscience and Cognitive Science: Neurobiology Emphasis", 0),
        ("Neuroscience and Cognitive Science: Philosophy of Mind Emphasis", 0),
        ("Physics", 0),
        ("Psychological Science", 0),
        ("Psychology", 3),
        ("Speech, Language and Hearing Sciences", 0),
        ("Statistics and Data Science", 0),
        ("Statistics and Data Science", 1),
    ]
